<?php 
include('includes/haut.php');
connexion_bdd();
$genus_name = define_genus();

?>
<script type="text/javascript">
	function allto1($type) {
		var inputs = document.getElementsByTagName('input');
		for(var i=0; i<inputs.length; i++) {
			if(inputs[i].className == $type) { inputs[i].value = 1; }
		}
	}
	
	function getXMLHttpRequest() {
		var xhr = null;
		if (window.XMLHttpRequest || window.ActiveXObject) {
			if (window.ActiveXObject) {
				try  {
					xhr = new ActiveXObject("Msxm12.XMLHTTP");
				} catch(e) {
					xhr = new ActiveXObject("Microsoft.XMLHTTP");
				}
			} else {
				xhr = new XMLHttpRequest();
			}
		} else {
			alert("Votre navigateur ne supporte pas l'objet XMLHttpRequest...");
			return null;
		}
		return xhr;
	}
	
	var xhr = getXMLHttpRequest();
	xhr.open("GET", "default_params.xml", false);
	xhr.send(null);
	var xmldoc = xhr.responseXML;
	
	function default_values($type) {
		if ('<?php echo $genus_name ?>' == 'Helicotylenchus' ) {
			var values = xmldoc.getElementsByTagName('genus')[1].getElementsByTagName('char');
		} else {
			var values = xmldoc.getElementsByTagName('genus')[0].getElementsByTagName('char');
		}

		var res = new Array();

		for (var i=0; i<values.length; i++) {
			var length = values[i].childNodes.length;
			var input_name = values[i].getAttribute('name');
			switch ($type) {
				case 'qt_weight': 
					if (length > 3) {
						res[i] = values[i].childNodes[1].firstChild.nodeValue;
						input_name = values[i].getAttribute("name").concat('_w');
					} break;
				case 'qt_correction': 
					if (length > 3) {
						res[i] = values[i].childNodes[3].firstChild.nodeValue;
						input_name = values[i].getAttribute("name").concat('_c');
					} break;
				case 'qt_rangeValue': 
					if (length > 3) {
						res[i] = values[i].childNodes[5].firstChild.nodeValue;
						input_name = values[i].getAttribute("name").concat('_r');
					} break;
				case 'ql_weight': 
					if (length == 3) {
						res[i] = values[i].childNodes[1].firstChild.nodeValue;
						input_name = values[i].getAttribute("name").concat('_w');
					} break;
			}
			
			var inputs = document.getElementsByTagName('input');
			for(var j=0; j<inputs.length; j++) {
				if (inputs[j].name == input_name) { 
				inputs[j].value = res[i]; }				
			}
		}
	}
	
	function verif_champs() {
		var inputs = document.getElementsByTagName('input');

		for(var i=0; i<inputs.length; i++) {
			if(inputs[i].type == 'text' && inputs[i].value == '') {
				alert("Error: All fields must be filled."); 
				return false;
			}
		}
		
		return true;
	}
	
	function get_weight() {
		var inputs = document.getElementsByTagName('input');
		var arr = {};
		
		for(var i=0; i<inputs.length; i++) {
			if(inputs[i].type == 'text' && inputs[i].name.indexOf("_w") !== -1) {
				arr[inputs[i].name]=inputs[i].value;
			}
		}
		return arr;
	}
	
</script>
<div id="new_sample">
	<ul>
	<li><h3>Upload a previously saved sample file: </h3></li>
		<form action="ftp.php" method="post" enctype="multipart/form-data">
			<input type="file" name="file" />
			<input type="hidden" name="file_type" value="sample" />
			<input type="submit" value="Upload" />
		</form>
		This file must be a .xml file generated by Nemaid 3.1.
	<br /><br />
	<li><h3>Or register a new sample now :</h3></li>
	<form name="new_sample" action="save.php" method="post">
		<tr><p><br />For each qualitative character, enter each state separately as the percentage of 
			specimens presenting that state. <br />Percentages must be entered as decimal values, 
			not as percents (e.g. enter 0.57 instead of 57%).</p></tr>
		<table>
			<tr><h3><br />Sample information</h3></tr>

				<tr>
					<td>Sample number</td>
					<td><input type="text" name="sample_id"></td>
				</tr>
				<tr>
					<td>Date of sampling</td>
					<td><input type="text" name="sample_date"></td>
				</tr>
				<tr>
					<td>Remarks</td>
					<td><textarea rows="3" name="remarks"></textarea></td>
				</tr>
			
			</table>
			<table>
			<tr><h3>Quantitative characters</h3></tr>
				
			<tr>
				<th>Characters</th>
				<th>Explanations</th>
				<th>Values</th>				
				<th>Weights</th>
				<th>Correction factors</th>
			</tr>
			<?php
				extract($_POST);
				if (file_exists("users_files/user".$_SESSION['user_id']."_params.xml") && get_xml_data('genus') == $genus_name) {
					$use_user_params = true; $user_params = get_xml_data('user_params');
					//echo "test";
				} else {
					$use_user_params = false;
					//echo "testfalse";
				}
				
				$query = mysql_query('SELECT code_char, name_char, explanations, weight, correction, max-min as rangeValue
									  FROM characters 
									  WHERE name_genus = "'.$genus_name.'" AND correction IS NOT NULL');
				
				while($row = mysql_fetch_row($query)){
					if($use_user_params) {
						$weight = $user_params[(string)$row["code_char"]]['weight'];
						$correction = $user_params[(string)$row["code_char"]]['correction'];
						$explanations = $user_params[(string)$row["code_char"]]['explanations'];
						$rangeValue = $ç[(string)$row["code_char"]]['rangeValue'];
					} else {
						$weight = sprintf('%.2f',round($row["weight"],2));
						$correction = sprintf('%.2f',round($row["correction"],2));
						$rangeValue = sprintf('%.2f',round($row["rangeValue"],2));
						$explanations = $user_params[(string)$row["code_char"]]['explanations'];
					}
						echo '<tr>';
						echo '	<td>'.$row[1];
						echo '	<td>'; if ($row[2] != NULL) echo $row[2]; echo'</td>';
						echo '	<td><input type="text" name="'.$row[0].'_v"></td>';
						echo '	<td><input class="qt_weight" type="text" name="'.$row[0].'_w" value="'.$row[3].'"></td>';
						echo '	<td><input class="qt_correction" type="text" name="'.$row[0].'_c" value="'.$row[4].'"></td>';
						echo '</tr>';
					
				}
			?>
				<tr>
				<th></th>
				<th></th>
				<th></th>
				<td>
					<input type="button" value="Set all to 1" onclick="allto1('qt_weight')">
					<br/>
					<input type="button" value="Defaults values" onclick="default_values('qt_weight')">
				</td>
				<td>
					<input type="button" value="Defaults values" onclick="default_values('qt_correction')">
				</td>
				<!--<td>
					<input type="button" value="Calculate range" onclick="default_values('qt_rangeValue')">
				</td> -->
			</tr>
			<tr><th><h3><br />Qualitative characters</h3></th></tr>
			
			<tr>
				<th>Characters</th>				
				<th>Values</th>
			</tr>
			<?php
				$query = mysql_query('SELECT code_char, name_char, explanations, nb_states 
									  FROM characters 
									  WHERE name_genus = "'.$genus_name.'" AND 
											correction IS NULL');
				
				while($row = mysql_fetch_row($query)){
				if(is_numeric(substr($row[1],-1))) $row[1] = substr($row[1],0,-1);
					
					if ($row[3] == 1) {
						echo '<tr>';
						echo '	<td>'.$row[1].'<SUP title="'.$row[2].'"></SUP></td>';
						echo '	<td><input type="text" name="'.$row[0].'_v"></td>';
						echo '</tr>';
					} elseif (substr($row[0], -1) == 1) {
						echo '<tr>';
						echo '	<td>'.$row[1].'</td>';
						echo '	<td><table><tr><td class="no_border"><input type="text" name="'.$row[0].'_v"></td><td class="no_border">'.$row[2].'</td></tr>'; 
					} elseif (substr($row[0], -1) == $row[3]){
						echo '	<tr><td class="no_border"><input type="text" name="'.$row[0].'_v"></td><td class="no_border">'.$row[2].'</table></td></tr>'; 
						echo '</tr>';
					} else {
						echo '	<tr><td class="no_border"><input type="text" name="'.$row[0].'_v"></td><td class="no_border">'.$row[2].'</td></tr>';
					}
				}
			?>
			
		</table>
		<br/><br/>
		<input type="hidden" name="file_type" value="sample">
		<input type="submit" value="Save sample" onclick="get_weight()">
		<!--<a href="users_files/18-user20_sample.xml" class="pagination">Click here to download an example of the "CSV" file</a>-->
	</form>
	</ul>
</div>

<?php
mysql_close();
?>
