<?php 
include('includes/haut.php');
connexion_bdd();
$genus_name = define_genus();
?>
<div id="new_sample">
	<ul>
	<li><h3>Upload a previously saved sample file: </h3></li>
		<form action="ftp.php" method="post" enctype="multipart/form-data">
			<input type="file" name="file" />
			<input type="hidden" name="file_type" value="sample" />
			<input type="submit" value="Upload" />
		</form>
		This file must be a .xml file generated by Nemaid 3.1.
	<br /><br />
	<li><h3>Or register a new sample now:</h3></li>
	<form action="save.php" method="post">
		<table>
			<tr><th><h3>Quantitative characters</h3></th></tr>			
			<tr>
				<th>Characters</th>
				<th>Values</th>
			</tr>
			<?php
				$query = mysql_query('SELECT code_char, name_char, explanations 
									  FROM characters 
									  WHERE name_genus = "'.$genus_name.'" AND 
											correction IS NOT NULL');
				
				while($row = mysql_fetch_row($query)){
					echo '<tr>';
					echo '	<td>'.$row[1]; if ($row[2] != NULL) echo '<SUP style="cursor:default;" title="'.$row[2].'"></SUP></td>';
					echo '	<td><input type="text" name="'.$row[0].'_v"></td>';
					echo '</tr>';
				}
			?>
			<tr><th><h3><br />Qualitative characters</h3></th></tr>
			<tr><p>For each qualitative character, enter each state separately as the percentage of 
			specimens presenting that state. <br />Percentages must be entered as decimal values, 
			not as percents (e.g. enter 0.57 instead of 57%).</p></tr>
			<tr>
				<th>Characters</th>				
				<th>Values</th>
			</tr>
			<?php
				$query = mysql_query('SELECT code_char, name_char, explanations, nb_states 
									  FROM characters 
									  WHERE name_genus = "'.$genus_name.'" AND 
											correction IS NULL');
				
				while($row = mysql_fetch_row($query)){
				if(is_numeric(substr($row[1],-1))) $row[1] = substr($row[1],0,-1);
					
					if ($row[3] == 1) {
						echo '<tr>';
						echo '	<td>'.$row[1].'<SUP title="'.$row[2].'"></SUP></td>';
						echo '	<td><input type="text" name="'.$row[0].'_v"></td>';
						echo '</tr>';
					} elseif (substr($row[0], -1) == 1) {
						echo '<tr>';
						echo '	<td>'.$row[1].'</td>';
						echo '	<td><table><tr><td class="no_border"><input type="text" name="'.$row[0].'_v"></td><td class="no_border">'.$row[2].'</td></tr>';
					} elseif (substr($row[0], -1) == $row[3]){
						echo '	<tr><td class="no_border"><input type="text" name="'.$row[0].'_v"></td><td class="no_border">'.$row[2].'</td></tr></table>';
						echo '</tr>';
					} else {
						echo '	<tr><td class="no_border"><input type="text" name="'.$row[0].'_v"></td><td class="no_border">'.$row[2].'</td></tr>';
					}
				}
			?>
			
			<tr><th><h3><br />Sample information</h3></th></tr>

			<tr>
				<td>Sample number</td>
				<td><input type="text" name="sample_id"></td>
			</tr>
			<tr>
				<td>Date of sampling</td>
				<td><input type="text" name="sample_date"></td>
			</tr>
			<tr>
				<td>Remarks</td>
				<td><textarea rows="3" name="remarks"></textarea></td>
			</tr>
		</table>
		<br/><br/>
		<input type="hidden" name="file_type" value="sample">
		<input type="submit" value="Save sample">
	</form>
	</ul>
</div>

<?php
mysql_close();
?>
